gis/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('/ind', 'HomeController@indica');

// Conversor
Route::get('init', ['as' => 'conversor.init', 'uses' => 'ConversorController@init']);
Route::get('conversor', ['as' => 'conversor.index', 'uses' => 'ConversorController@index']);
Route::post('conversor/upload', ['as' => 'conversor.upload', 'uses' => 'ConversorController@upload']);
Route::get('conversor/todos', 'ConversorController@converterTodos');
Route::get('conversor/todoscomcurso', 'ConversorController@converterTodosComCurso');
Route::get('conversor/areacursos/converter', 'ConversorController@converterAreaCurso');
Route::get('conversor/qualis/converter', 'ConversorController@converterQualis');
Route::get('conversor/teste', ['as' => 'conversor.teste', 'uses' => 'ConversorController@teste']);

// GIS UECE
Route::namespace('Gis')->prefix('gis')->name('gis.')->group(function () {
    //Done
    Route::get('titulacoes', ['as' => 'titulacoes', 'uses' => 'TitulacoesController@index']);
    Route::get('titulacoes/instituicao/{instituicao}', ['as' => 'titulacoes.instituicao', 'uses' => 'TitulacoesController@instituicao']);
    Route::get('titulacoes/estatisticas', ['as' => 'titulacoes.estatisticas', 'uses' => 'TitulacoesController@estatisticas']);
    Route::get('titulacoes/pais/{sigla}', ['as' => 'titulacoes.pais', 'uses' => 'TitulacoesController@pais']); 
});

// Indica UECE
Route::namespace('Ind')->prefix('ind')->name('ind.')->group(function () {
    //Done
    Route::get('centers', 'CentersController@index')->name('centers');
    Route::get('centerDetais/{id}', 'CentersController@centerDetails')->name('centerDetails');
    Route::get('professors', 'ProfessorsController@index')->name('professors');
    Route::get('professorDetails/{id}', 'ProfessorsController@professorDetails')->name('professorDetails');
    Route::get('compararProfessores/{nome1}/{nome2}', 'ProfessorsController@compararProfessores')->name('compararProfessores');
    Route::get('general', 'GeneralController@index')->name('general');
    Route::get('destaques', 'GeneralController@destaques')->name('destaques');
    Route::get('comparar', 'GeneralController@comparar')->name('comparar');
    Route::get('compararCentros/{centro1}/{centro2}', 'GeneralController@compararCentros')->name('compararCentos');
    Route::get('qualis', 'QualisController@index')->name('qualis');
    Route::get('indica', 'HomeController@indica')->name('indica');
    
    

});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

gis/app/Http/Controllers/Api/Ind/V1/BuscaController.php
<?php

namespace Gis\Http\Controllers\Api\Ind\V1;

use Gis\Models\Aperfeicoamento;
use Gis\Models\Doutorado;
use Gis\Models\Especializacao;
use Gis\Models\Graduacao;
use Gis\Models\Lattes;
use Gis\Models\LivreDocencia;
use Gis\Models\Mestrado;
use Gis\Models\MestradoProfissionalizante;
use Gis\Models\PosDoutorado;
use Gis\Http\Controllers\Controller;
use Gis\Models\ResidenciaMedica;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BuscaController extends Controller
{

    public function  getArtigosPubPorAno()
    {

        $jsonurl = "http://localhost:9000/ind/publishStatisticsByYear";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->articles;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano_do_artigo);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $ArtigoAno['labels'] = $labels;
        $ArtigoAno['values'] = $values;
        return response()->json($ArtigoAno);
    }


    // Busca trabalhos em eventos X ano no banco
    public function getTrabEvePorAno()
    {
        $jsonurl = "http://localhost:9000/ind/publishStatisticsByYear";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->events;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $trabAno['labels'] = $labels;
        $trabAno['values'] = $values;
        return response()->json($trabAno);
    }

    //Retorna a quantidade de capitulos de livros publicados por ano

    public function getQuantCapDeLivrosPorAno()
    {
        $jsonurl = "http://localhost:9000/ind/publishStatisticsByYear";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->books;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }
        $capLivros['labels'] = $labels;
        $capLivros['values'] = $values;
        return response()->json($capLivros);
    }


    public function getQualisPorAno()
    {
        $jsonurl = "http://localhost:9000/ind/qualisStatistics";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->results;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->estrato);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }
        $qualisAno['labels'] = $labels;
        $qualisAno['values'] = $values;
        //dd($qualisAno);
        return response()->json($qualisAno);
    }

    public function atualizaQualis(Request $request)
    {
        $ano = $request->ano;
        $jsonurl = "http://localhost:9000/ind/qualisStatisticsByYear/$ano";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->results;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->estrato);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $qualisAno = $jsonresult->results;
        
        $qualisAno['labels'] = $labels;
        $qualisAno['values'] = $values;
        //dd($qualisAno);
        return response()->json($qualisAno);

    }

    public function getQualisPorEstrato()
    {

        $jsonurl = "http://localhost:9000/ind/qualisStatisticsByRank/A1";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->results;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano_do_artigo);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $qualisEstrato = $jsonresult->results;
        
        $qualisEstrato['labels'] = $labels;
        $qualisEstrato['values'] = $values;
        //dd($qualisEstrato);

        return response()->json($qualisEstrato);
    }

    public function atualizaQualisPorEstrato(Request $request)
    {
        $estrato = $request->estrato;
        $jsonurl = "http://localhost:9000/ind/qualisStatisticsByRank/$estrato";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->results;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano_do_artigo);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $qualisEstrato = $jsonresult->results;
        
        $qualisEstrato['labels'] = $labels;
        $qualisEstrato['values'] = $values;
        //dd($qualisEstrato);

        return response()->json($qualisEstrato);
    }


    public function  getArtigosPubPorAnoCentro($id){

        $jsonurl = "http://localhost:9000/ind/publishedArticlesFromCenterStatistics/$id";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->articles;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano_do_artigo);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $ArtigoAno = $jsonresult->articles;
        
        $ArtigoAno['labels'] = $labels;
        $ArtigoAno['values'] = $values;
        return response()->json($ArtigoAno);
    }

    public function getQuantCapLivrosCentro($id)
    {
        $jsonurl = "http://localhost:9000/ind/publishedArticlesFromCenterStatistics/$id";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->books;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $capLivros = $jsonresult->books;
        
        $capLivros['labels'] = $labels;
        $capLivros['values'] = $values;

        return response()->json($capLivros);
    }

    public function getQuantEventosCentro($id)
    {
        $jsonurl = "http://localhost:9000/ind/publishedArticlesFromCenterStatistics/$id";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->events;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->ano);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $trabAno = $jsonresult->events;
        
        $trabAno['labels'] = $labels;
        $trabAno['values'] = $values;
        return response()->json($trabAno);
    }

    public function atualizaQualisCentro(Request $request)
    {
        //dd($request);

        $id = $request->id;
        $ano = $request->ano;

        $jsonurl = "http://localhost:9000/ind/qualisStatisticsByCenter/$id/$ano";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->results;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->estrato);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $qualisAno = $jsonresult->results;
        
        $qualisAno['labels'] = $labels;
        $qualisAno['values'] = $values;


        return response()->json( $qualisAno);

    }

    public function qualisPorAnoCentro($id)
    {
        $jsonurl = "http://localhost:9000/ind/qualisStatisticsByCenter/$id/1970";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $results = (object) $jsonresult->results;
        $labels = array();
        foreach ($results as $result){
            array_push($labels , $result->estrato);
        }
        $values = array();
        foreach ($results as $result){
            array_push($values , $result->count);
        }

        $qualisAno = $jsonresult->results;
        
        $qualisAno['labels'] = $labels;
        $qualisAno['values'] = $values;
        //dd($qualisAno);
        return response()->json($qualisAno);
    }
}

gis/app/Http/Controllers/Ind/CentersController.php
<?php

namespace Gis\Http\Controllers\Ind;
use Gis\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class CentersController extends Controller
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

public function index(){
    $page_title = 'Indicadores por Centros';

    $jsonurl = "http://localhost:9000/ind/centers";
    $json = file_get_contents($jsonurl);
    $jsonresult = json_decode($json);
    $centros = $jsonresult->results;

    //dd($centros);
    return view('ind/centers', compact(['page_title','centros']));
}


    public function centerDetails($id){
        $page_title = 'Indicadores por Centros';

        $jsonurl = "http://localhost:9000/ind/centersSpecific/$id";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        
        $centro = $jsonresult->results[0];

        $sigla = $centro->sigla;
        $nome = $centro->nome;
        
        // Busca a quantidade de professores com Lattes
        $jsonurl = "http://localhost:9000/ind/teachersFromCenter/$id/count=true";
        $json = file_get_contents($jsonurl);
        $numDeProfessores = $json;
        // Busca a quantidade de cursos Cadastradoss no Banco
        $jsonurl = "http://localhost:9000/ind/universityCoursesFromCenter/$id/count=true";
        $json = file_get_contents($jsonurl);
        $qtdCursos = $json;

        $jsonurl = "http://localhost:9000/ind/articleYear/$id";
        $json = file_get_contents($jsonurl);
        $jsonresult = json_decode($json);
        $anos = $jsonresult->results;
        
        $jsonurl = "http://localhost:9000/ind/publishedArticlesFromCenter/$id/count=true";
        $json = file_get_contents($jsonurl);
        $artigosPub = $json;

        $jsonurl = "http://localhost:9000/ind/eventsWorksFromCenter/$id/count=true";
        $json = file_get_contents($jsonurl);
        $trabEventos = $json;
        
        $jsonurl = "http://localhost:9000/ind/publishedCapBooksFromCenter/$id/count=true";
        $json = file_get_contents($jsonurl);
        $capLivros = $json;
        
        return view('ind/centerDetails', compact(['page_title','numDeProfessores','qtdCursos','anos','artigosPub','trabEventos','capLivros','id','sigla','nome']));

    }


}

gis/app/Http/Controllers/Ind/QualisController.php
<?php

namespace Gis\Http\Controllers\Ind;
use Gis\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class QualisController extends Controller
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

public function index(){

    $jsonurl = "http://localhost:9000/ind/qualisStatistics";
    $json = file_get_contents($jsonurl);
    $jsonresult = json_decode($json);
    $results = (object) $jsonresult->results;
    $estratos = array();
    foreach ($results as $result){
        array_push($estratos , $result->estrato);
    }

    $estratosCount = $jsonresult->results;
    
    $jsonurl = "http://localhost:9000/ind/articleYear";
    $json = file_get_contents($jsonurl);
    $jsonresult = json_decode($json);
    $anos = $jsonresult->results;
    
    $jsonurl = "http://localhost:9000/ind/publishedArticles/count=true";
    $json = file_get_contents($jsonurl);
    $totalArtigosPublicados = (int) $json;

    $jsonurl = "http://localhost:9000/ind/publishedArticlesWithoutQualis";
    $json = file_get_contents($jsonurl);
    $artigosSemQualis = (int) $json;
    
    return view('ind/qualis', compact(['estratos','anos','estratosCount','totalArtigosPublicados','artigosSemQualis']));

}


}

gis/resources/views/ind/centers.blade.php
@extends('layout.page2')


@section('content')


    @foreach($centros as $centro)
        <a href="{{route('ind.centerDetails',$centro->id)}}">
        <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-light-blue-active">
            <span class="info-box-icon"><i class="fa fa-graduation-cap"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">{{ $centro->nome }}</span>
                <span class="info-box-number">{{ $centro->sigla }}</span>

                <div class="progress">
                    <div class="progress-bar" ></div>
                </div>
                <span class="progress-description">
                UECE
              </span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
        </div>
        </a>

    @endforeach

@endsection

gis/resources/views/ind/comparar.blade.php
@extends('layout.page2')


@section('content')

    <h1> Comparar </h1>

    <div class="content box box-default" >

        <h2> Centros </h2>

        <div class="row col-md-12">
            <div  class="col-sm-4">
                <select id="centro1" class="form-control col-sm-4">
                    @foreach($centros as $centro)
                        <option>{{$centro->sigla}}</option>
                    @endforeach
                </select>
            </div>

            <div  class="col-sm-4">
                <select id="centro2" class="form-control col-sm-4">
                    @foreach($centros as $centro)
                        <option>{{ $centro->sigla}}</option>
                    @endforeach
                </select>
            </div>

            <div  id="comparaCentro" class="col-sm-2"><button type="button" class="btn btn-block btn-primary col-sm-4">Comparar Centros</button></div>


        </div>

        <br>

        <h2> Professores </h2>

        <div class="row col-md-12">
            <div  class="col-sm-4">
                <select id="professor1" class="form-control col-sm-4">
                    @foreach($professores as $professor)
                    <option>{{ $professor->nome_completo }}</option>
                    @endforeach
                </select>
            </div>

            <div  class="col-sm-4">
                <select id="professor2" class="form-control col-sm-4">
                    @foreach($professores as $professor)
                        <option>{{ $professor->nome_completo }}</option>
                    @endforeach
                </select>
            </div>

            <div  id="comparaProfessor" class="col-sm-2"><button type="button" class="btn btn-block btn-primary col-sm-4">Comparar Professores</button></div>


        </div>


    </div>


@endsection

@section('js')
    <script>

        $("#comparaCentro").click(function() {
            var e = document.getElementById("centro1");
            var strCentro1 = e.options[e.selectedIndex].value;
            var e = document.getElementById("centro2");
            var strCentro2 = e.options[e.selectedIndex].value;
            window.location.href="compararCentros/" +strCentro1 + "/" + strCentro2;

        });


        $("#comparaProfessor").click(function() {
            var e = document.getElementById("professor1");
            var strProf1 = e.options[e.selectedIndex].value;
            var e = document.getElementById("professor2");
            var strProf2 = e.options[e.selectedIndex].value;
            window.location.href="compararProfessores/" +strProf1 + "/" + strProf2;

        });




    </script>

@endsection

gis/resources/views/ind/destaques.blade.php
@extends('layout.page2')


@section('content')


<h1> Destaques </h1>

<div class="content box box-default" >
    <h2>Artigos Publicados</h2>

    <div id = 'dtBasicExample' class="table-responsive ">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Professor</th>
                <th>Número de Artigos Publicados</th>

            </tr>
            </thead>
            <tbody>
            @foreach($profArtigos as $profArtigo)
                <tr>
                    <td><a href="{{route('ind.professorDetails',$profArtigo->lattes_id)}}">{{ $profArtigo->name }}</a></td>
                    <td>{{ $profArtigo->ART }}</td>

                </tr>

            @endforeach
            </tbody>
        </table>
    </div>



    <h2>Trabalhos em Eventos</h2>

    <div id = 'dtBasicExample' class="table-responsive ">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Professor</th>
                <th>Número de Trabalhos em Eventos</th>

            </tr>
            </thead>
            <tbody>
            @foreach($profEventos as $profEvento)
                <tr>
                    <td><a href="{{route('ind.professorDetails',$profEvento->lattes_id)}}">{{ $profEvento->name }}</a></td>
                    <td>{{ $profEvento->ART }}</td>

                </tr>

            @endforeach
            </tbody>
        </table>
    </div>


    <h2>Capítulos de Livros</h2>

    <div id = 'dtBasicExample' class="table-responsive ">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr>
                <th>Professor</th>
                <th>Número de Capítulos de Livros</th>

            </tr>
            </thead>
            <tbody>
            @foreach($profCapLivros as $profCapLivro)
                <tr>
                    <td><a href="{{route('ind.professorDetails',$profCapLivro->lattes_id)}}">{{ $profCapLivro->name }}</a></td>
                    <td>{{ $profCapLivro->ART }}</td>

                </tr>

            @endforeach
            </tbody>
        </table>
    </div>



</div>




@endsection

@section('js')
    <script>


    </script>



@endsection

gis/resources/views/ind/indicaHome.blade.php
@extends('layout.page2')

@section('content')

        <div class="row">

            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>Visão Geral</h3>

                        <p>Visão Geral dos Indicadores</p>
                    </div>
                    <div class="icon">
                        <i class="ion-eye"></i>
                    </div>
                    <a href="{{ route('ind.general') }}" class="small-box-footer">
                        Ver <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3>Centros</h3>

                        <p>Indicadores dos Centros</p>
                    </div>
                    <div class="icon">
                        <i class="ion-stats-bars"></i>
                    </div>
                    <a href="{{ route('ind.centers') }}" class="small-box-footer">
                        Ver <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>



        </div>
        <div class="row">


            <!-- /.col -->
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>Professores</h3>

                        <p>Professores Cadastrados</p>
                    </div>
                    <div class="icon">
                        <i class="ion-university"></i>
                    </div>
                    <a href="{{ route('ind.professors') }}" class="small-box-footer">
                        Ver <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>Qualis - Artigos</h3>

                        <p>Qualis dos Artigos Publicados</p>
                    </div>
                    <div class="icon">
                        <i class="ion-trophy"></i>
                    </div>
                    <a href="{{ route('ind.qualis') }}" class="small-box-footer">
                        Ver <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>


        </div>
        <div class="row">


            <!-- /.col -->
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="small-box bg-primary">
                    <div class="inner">
                        <h3>Destaques</h3>

                        <p>Destaques de produção</p>
                    </div>
                    <div class="icon">
                        <i class="ion-star"></i>
                    </div>
                    <a href="{{ route('ind.destaques') }}" class="small-box-footer">
                        Ver <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="small-box bg-teal-active">
                    <div class="inner">
                        <h3>Comparar</h3>

                        <p>Comparar centros ou Professores</p>
                    </div>
                    <div class="icon">
                        <i class="ion-search"></i>
                    </div>
                    <a href="{{ route('ind.comparar') }}" class="small-box-footer">
                        Ver <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>


        </div>






@stop

gis/resources/views/ind/professors.blade.php
@extends('layout.page2')


@section('content')

    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover dataTables">
            <thead>
            <tr>
                <th>Professor</th>
                <th>Citação</th>
                <th>Ultima Atualização</th>
                <th>Nacionalidade</th>
            </tr>
            </thead>
            <tbody>
            @foreach($professores as $professor)
                    <tr>
                        <td><a href="{{route('ind.professorDetails',$professor->id)}}">{{ $professor->nome_completo }}</a></td>
                        <td>{{ $professor->nome_citacao }}</td>
                        <td>{{ $professor->data_atualizacao }}</td>
                        <td>{{ $professor->nacionalidade }}</td>
                    </tr>

            @endforeach
            </tbody>
        </table>
    </div>


@endsection